name: Tidy

on:
  push: {}

jobs:
  tidy:
    name: 'Ensure repository is tidy'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Deps
        run: node common/scripts/install-run-rush.js install
      - name: Lint and fix all auto-fixable problems
        run: node common/scripts/install-run-rush.js lint-fix
        if: always()
      - name: Make sure all source code is formatted using Prettier
        run: node common/scripts/install-run-rush.js format-all
        if: always()
      - run: git add --update
      - uses: dtinth/patch-generator-action@main
